//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmotahidaTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesDetail
    {
        public int tblItem { get; set; }
        public int tblSalesHeader { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual tblItem tblItem1 { get; set; }
        public virtual tblSalesHeader tblSalesHeader1 { get; set; }
    }
}
