//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlmotahidaTask.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSalesHeader()
        {
            this.tblSalesDetails = new HashSet<tblSalesDetail>();
        }
    
        public int gISerial { get; set; }
        public Nullable<int> tblCustomer { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    
        public virtual tblCustomer tblCustomer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesDetail> tblSalesDetails { get; set; }
    }
}
